### ISSUE TITLE
hi,i use your net to train faceDetector,but it does not work

### ISSUE THREAD

**Issue by zhangyunming** [lampsonSong/tinySSD#1]
hi, last day i used your train.prototxt with widerface to train a face detector . though test with your test.prototxt with fddb have a 88 mAP, when inference with your deploy.prototxt on video,it detect nothing.

what is the problom?

thanks

**Comment by lampsonSong** [comment]
@zhangyunming  hi, 之前的东西有一些错误，就放上来了，正在改进。改好了会放上来，不好意思啊。

**Comment by nonobelong** [comment]
@lampsonSong 大概什么时候会放上来？好期待

**Comment by lampsonSong** [comment]
@nonobelong 放上来了

**Comment by lampsonSong** [comment]
@zhangyunming Could you check our new released model and prototxt if you still need it
