### ISSUE TITLE
Kernel keeps running after running detect

### ISSUE THREAD

**Issue by akshagu** [lampsonSong/tinySSD#6]
I was trying to time the detect operation and could not obtain an output. I then imported the script to a jupyter notebook and realized that the kernel keeps running after giving the detect command and never stops even after producing the output. I wanted to know what I was doing wrong while running the model.
![image](https://user-images.githubusercontent.com/44054594/46794423-c0f3a380-cd15-11e8-9d5a-5f7b530a26f2.png)

**Comment by lampsonSong** [comment]
@akshagu Hi, it is normal. Because we write a cv::waitKey(0) at the end of detect(), the program would be handed on. By the way, the demo.py script is written followed python2. You can try using python 2.
